// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjjzEu2DoUhnJcNw4LIZWrrHGmZJBlFWs',
    appId: '1:428756239544:web:c125ccd71433534ea6e04d',
    messagingSenderId: '428756239544',
    projectId: 'pill-tracker-e971a',
    authDomain: 'pill-tracker-e971a.firebaseapp.com',
    storageBucket: 'pill-tracker-e971a.appspot.com',
    measurementId: 'G-GT2S5BF08G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD79A_N6YamRwSU5mrcmLlickFJEO7HOs',
    appId: '1:428756239544:android:0278c3aae4d6ddc5a6e04d',
    messagingSenderId: '428756239544',
    projectId: 'pill-tracker-e971a',
    storageBucket: 'pill-tracker-e971a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd4Z9SzBH_olAOImBQsW30cYT5VlIiLzE',
    appId: '1:428756239544:ios:4e1e6960cbee76bba6e04d',
    messagingSenderId: '428756239544',
    projectId: 'pill-tracker-e971a',
    storageBucket: 'pill-tracker-e971a.appspot.com',
    iosClientId: '428756239544-ugu4lhahijdp9lfofcfp80vsqsatu4d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.pillTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd4Z9SzBH_olAOImBQsW30cYT5VlIiLzE',
    appId: '1:428756239544:ios:c8e81dd3982d8448a6e04d',
    messagingSenderId: '428756239544',
    projectId: 'pill-tracker-e971a',
    storageBucket: 'pill-tracker-e971a.appspot.com',
    iosClientId: '428756239544-vfim1mgq9ihvjuht900a9bghe10ctub4.apps.googleusercontent.com',
    iosBundleId: 'com.example.pillTrackerApp.RunnerTests',
  );
}
